title: I'd Rather Be Telling Stories
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://idratherbetellingstories.com
baseurl: ""
paginate_path: "blog/page:num/"
#permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact
 - title: Subscribe
   url: /subscribe
 - title: Flickr
   url: /flickr
 - title: Archives
   url: /archives

social:
   github: tomjohnson1492
   twitter: tomjohnson
   facebook: tomjohnson1492
   email: tomjohnson1492@gmail.com

# google_analytics: "UA-58263416-1"

permalink: /:year/:month/:day/:title/
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: true
